## Arithmetic with NumPy Arrays

In [1]:
import numpy as np

In [2]:
dataSetX = [1.,2.,3.,4.]
dataSetY = [5.,6.,7.,8.]

In [6]:
arr1 = np.array([dataSetX, dataSetY])

In [7]:
arr1

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [8]:
# check dimension

arr1.ndim

2

In [9]:
# check shape

arr1.shape

(2, 4)

In [10]:
# check data type

arr1.dtype

dtype('float64')

#### Multiplication

In [12]:
arr1 * arr1

array([[ 1.,  4.,  9., 16.],
       [25., 36., 49., 64.]])

#### Subtraction 

In [13]:
arr1 - arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
1/arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [19]:
price_per_unit = np.array([1000,400,1200])

In [20]:
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [26]:
final_product = np.dot(price_per_unit,units)

In [22]:
price_per_unit.ndim

1

In [23]:
units.ndim

2

In [24]:
units.shape

(3, 3)

In [25]:
price_per_unit.shape

(3,)

In [28]:
final_product ** 0.5

array([185.47236991, 223.60679775, 253.77155081])

In [30]:
iPhone_dataSet = np.array([[0.,4,1],[4.4,1,5.1]])

In [31]:
iPhone_dataSet

array([[0. , 4. , 1. ],
       [4.4, 1. , 5.1]])

In [32]:
iPhone_dataSet.dtype

dtype('float64')

In [33]:
iPad_dataSet = np.array([[0.0,4.1,1.0],[4.,1,5.1]])

In [35]:
iPad_dataSet

array([[0. , 4.1, 1. ],
       [4. , 1. , 5.1]])

In [36]:
iPhone_dataSet > iPad_dataSet

array([[False, False, False],
       [ True, False, False]])

In [37]:
iPad_dataSet > iPhone_dataSet

array([[False,  True, False],
       [False, False, False]])