## Anonymous (Lambda) Functions

In [3]:
import numpy as np

In [1]:
def normal_function(param1):
    return param1 * 2

In [2]:
print(normal_function(2))

4


In [15]:
square = lambda param1: param1 * 2

In [16]:
print(square(2))

4


In [17]:
def normal_function2(param):
    print(param)

In [18]:
normal_function2(square)

<function <lambda> at 0x7fb13410f4c0>


In [21]:
def apply_to_list(lst,f):
    return [f(x) for x in lst]


myList = [4,5,3,1,7]

apply_to_list(myList,lambda x : x**2)

[16, 25, 9, 1, 49]

In [22]:
import numpy as np

In [23]:
my_arr = np.arange(1000000)

In [24]:
my_list = list(range(1000000))

In [25]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 20.7 ms, sys: 17.9 ms, total: 38.6 ms
Wall time: 37.8 ms


In [26]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

CPU times: user 297 ms, sys: 170 ms, total: 467 ms
Wall time: 465 ms


In [38]:
data = np.array([[1,2,3],[4,5,6]])

In [39]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
data * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [43]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [44]:
data = np.random.randn(2,3)

In [58]:
data

array([[-1.16471564,  0.25664773, -0.34404476],
       [ 1.38141875,  0.84882524, -0.25231339]])

In [59]:
data * 10

array([[-11.64715638,   2.56647726,  -3.44044763],
       [ 13.81418748,   8.48825243,  -2.52313394]])

In [60]:
data + data

array([[-2.32943128,  0.51329545, -0.68808953],
       [ 2.7628375 ,  1.69765049, -0.50462679]])

In [52]:
lst = ['kajol','madam','nitin','naman','narin']

for i in lst:
    if i == i[::-1]:
        print(i)

madam
nitin
naman


In [53]:
#print the elements having length greater than  5 from the list.

k = ['python','data','analyst','DS']

for i in k:
    if len(i) > 5:
        print(i)

python
analyst


In [54]:
# print the elements having even length

for i in k:
    if len(i) % 2 == 0:
        print(i)

python
data
DS


In [55]:
# print the reverse of every element in list 

z = ['python','java','data','scientist']

for i in z:
    print(i[::-1])

nohtyp
avaj
atad
tsitneics


### Creating ndarrays

In [62]:
data1 = [6,7.5,8,0,1]

arr1 = np.array(data1)

In [63]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [65]:
# print the reverse of element if it is palindrome else print the length 
lst = ['kajol','madam','nitin','naman','narin']

for x in lst:
    if x == x[::-1]:
        print(len(x))
    else:
        print(x[::-1])


lojak
5
5
5
niran


In [67]:
arr1.shape

(5,)

In [69]:
arr1.dtype

dtype('float64')

In [70]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

In [71]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [72]:
arr2.shape

(2, 4)

In [73]:
arr2.dtype

dtype('int64')

In [74]:
arr2.ndim

2

In [75]:
arr1.ndim

1

In [85]:
# print the multiples of 5 which are greater than 25 in range of 1 to 100

for i in range(1,101):
    if i %5 == 0 and i > 25:
        print(i)

30
35
40
45
50
55
60
65
70
75
80
85
90
95
100


In [87]:
[x for x in range(1,101) if x%5==0 and x>25]

[30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]

In [88]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])

expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [89]:
profit_loss = revenue - expenses

In [90]:
profit_loss

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [1]:
data3 = [[1,2,3,4],[5,6,7,8]]

In [5]:
arrData3 = np.array(data3)

In [31]:
arrData3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
# check the shape and dimensions of arrData3

arrData3.shape

(2, 4)

In [8]:
arrData3.ndim

2

In [10]:
arrData3.dtype

dtype('int64')

In [27]:
zMatrix = np.zeros(10)

In [15]:
zerosMatrix = np.zeros((3,2))

In [16]:
zerosMatrix.dtype

dtype('float64')

In [17]:
zerosMatrix.ndim

2

In [18]:
zerosMatrix.shape

(3, 2)

In [19]:
zerosMatrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
emptyMatrix = np.empty((2,3))

In [21]:
emptyMatrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
emptyMatrix.dtype

dtype('float64')

In [23]:
emptyMatrix.shape

(2, 3)

In [24]:
emptyMatrix.ndim

2

In [26]:
arangeMatrix = np.arange(10)

In [28]:
np.array([arangeMatrix,zMatrix])

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
lst = [1,4,5,2,4]

asArray = np.asarray(lst)

In [30]:
asArray

array([1, 4, 5, 2, 4])

In [32]:
asArray.dtype

dtype('int64')

In [33]:
lst1 = [1.1,1.6,1.3,2.5]

asArray1 = np.asarray(lst1)

In [34]:
asArray1

array([1.1, 1.6, 1.3, 2.5])

In [35]:
tp = (2,3,4,5,6)

tpArr = np.array(tp)

In [36]:
tpArr

array([2, 3, 4, 5, 6])

In [37]:
tpArr.ndim

1

In [38]:
tpArr.dtype

dtype('int64')

### Data types for ndarrays

In [39]:
arr1 = np.array([1,2,3,4],dtype=np.float64)

In [40]:
arr1

array([1., 2., 3., 4.])

In [53]:
arr1=np.array(tpArr)

In [54]:
arr1

array([2, 3, 4, 5, 6])

In [55]:
arr1.dtype

dtype('int64')

In [56]:
arr1.astype(np.float64)

array([2., 3., 4., 5., 6.])

In [57]:
arr1.dtype

dtype('int64')

In [58]:
arr1

array([2, 3, 4, 5, 6])

In [48]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [49]:
arr.dtype

dtype('int64')

In [50]:
float_arr = arr.astype(np.float64)

float_arr

array([1., 2., 3., 4.])

In [51]:
float_arr.dtype

dtype('float64')

In [6]:
lst=[565,100,555,934,404]

print(type(lst))

<class 'list'>


In [7]:
lst

[565, 100, 555, 934, 404]

In [5]:
[str(x) for x in lst]

['565', '100', '555', '934', '404']

In [9]:
palindrom_lst = [str(x) for x in lst]

In [11]:
palindrom_lst = [x for x in palindrom_lst if x == x[::-1]]

In [12]:
palindrom_lst

['565', '555', '404']

In [13]:
[int(x) for x in palindrom_lst]

[565, 555, 404]

In [14]:
def filterPalindrom(num):
    return str(num) == str(num)[::-1]

In [15]:
normal_distList = [565, 100, 555, 934, 404]

In [16]:
normal_distList

[565, 100, 555, 934, 404]

In [17]:
palindrom_list = [x for x in normal_distList if filterPalindrom(x)]

In [18]:
palindrom_list

[565, 555, 404]