#### Creating NumPy Array - 1D Array [Vector]

In [5]:
a=[1,2,3,4]

myArr1 = np.array(a)

In [6]:
myArr1

array([1, 2, 3, 4])

In [7]:
myarr = np.array([4,5,6,7])

In [8]:
myarr.ndim

1

In [14]:
[x*2 for x in myarr]

[8, 10, 12, 14]

#### 2D Array [Matrix]

In [3]:
import numpy as np

In [2]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

npMatrix = np.array(matrix)

npMatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
npMatrix.ndim # this is to check the dimension of array

2

In [9]:
npMatrix.shape # shape gives you the count of rows and colums

(3, 3)

### Numpy Functions / Methods

In [1]:
# 1. zeros

In [4]:
arr=np.zeros(5)

arr

array([0., 0., 0., 0., 0.])

In [5]:
arr2 = np.zeros((2,3))

In [6]:
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# 2. ones

In [8]:
myArr1 = np.ones(5)

In [9]:
myArr1

array([1., 1., 1., 1., 1.])

In [10]:
myArr2 = np.ones((3,4))

In [11]:
myArr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
# 3. eye - This function creates an array with all the diagonal elements as 1 and rest as 0

In [13]:
sqMatrix = np.eye(3)

In [14]:
sqMatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
sqMatrix2 = np.eye(3,5)

In [17]:
sqMatrix2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [18]:
# 4. diag - Diagonal element


In [22]:
myDiag1 = np.diag([5,7,8])

myDiag1

array([[5, 0, 0],
       [0, 7, 0],
       [0, 0, 8]])

In [23]:
np.diag(myDiag1)

array([5, 7, 8])

In [24]:
np.diag(sqMatrix)

array([1., 1., 1.])

In [25]:
myDiag2 = np.diag([1,2,3])

myDiag2

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [26]:
myDiag1 + myDiag2

array([[ 6,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [27]:
myDiag1 * myDiag2

array([[ 5,  0,  0],
       [ 0, 14,  0],
       [ 0,  0, 24]])

In [28]:
myDiag1 % myDiag2

/tmp/ipykernel_3785/1357120037.py:1: RuntimeWarning: divide by zero encountered in remainder
  myDiag1 % myDiag2


array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [29]:
myDiag1 / myDiag2

/tmp/ipykernel_3785/1604888183.py:1: RuntimeWarning: invalid value encountered in divide
  myDiag1 / myDiag2


array([[5.        ,        nan,        nan],
       [       nan, 3.5       ,        nan],
       [       nan,        nan, 2.66666667]])

In [30]:
''' 
5. randint - This function is used to generate a random number 
between a given range

the syntax is - rand(min,max,total_values)
'''

' 5. randint - This function is used to generate a random number \nbetween a given range\n\nthe syntax is - rand(min,max,total_values)\n\n'