In [1]:
import numpy as np

In [2]:
'''
1D Array = VECTOR
2D Array = MATRIX
nD Array = TENSOR
'''

'\n1D Array = VECTOR\n2D Array = MATRIX\nnD Array = TENSOR\n'

In [3]:
# Create a 2D numpy array
matrixA = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
# Display the original matrix
print('Original Matrix:')
print(matrixA)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Basic slicing examples

In [5]:
# print the first row
print(f"First Row : {matrixA[0]}")

First Row : [1 2 3]


#### Multidimensional Slicing: For multidimensional arrays, you can use a comma-separated tuple of slice objects. For example, array[start1:stop1:step1, start2:stop2:step2] will slice a 2D array.

In [6]:
# print the second column

print(f"Second Column : {matrixA[:,1]}")

Second Column : [2 5 8]


In [7]:
# print the thrid row

print(f"Third Row : { matrixA[2] }")

Third Row : [7 8 9]


In [8]:
# print the last row

print(f"Last row : {matrixA[-1]}")

Last row : [7 8 9]


### Slice with steps

In [9]:
print('\nSlicing with Steps:')


Slicing with Steps:


In [11]:
matrixA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
print(f"Every second element of first row : {matrixA[0, ::2]}")

Every second element of first row : [1 3]


In [31]:
# Slicing a submatrix
print('\nSlicing a Submatrix:')
print(f"Top left 2x2 submatrix:\n{ matrixA[:2, :2] } ")


Slicing a Submatrix:
Top left 2x2 submatrix:
[[1 2]
 [4 5]] 


In [32]:
# Using negative indices
print('\nUsing Negative Indices:')
print('Bottom right element:', matrixA[-1, -1])


Using Negative Indices:
Bottom right element: 9


In [33]:
# Using slices with steps
print('\nUsing Slices with Steps:')
print('Reversed first row:', matrixA[0, ::-1])


Using Slices with Steps:
Reversed first row: [3 2 1]


In [52]:
matrixA[:,::-1] # reverse the matrix

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [53]:
revMatrixA_1 = matrixA[:,::-1]

In [54]:
revMatrixA_1

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [57]:
matrixA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
matrixB = matrixA + revMatrixA_1

In [56]:
matrixB

array([[ 4,  4,  4],
       [10, 10, 10],
       [16, 16, 16]])

In [58]:

# Using boolean indexing
bool_idx = (matrixA % 2 == 0) # Find even elements
print('\nUsing Boolean Indexing:')
print('Even elements:', matrixA[bool_idx])


Using Boolean Indexing:
Even elements: [2 4 6 8]


In [59]:
matrixA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
matrixA[:2,1:]

array([[2, 3],
       [5, 6]])

In [63]:
matrixA[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [68]:
matrixA[:2,:2]

array([[1, 2],
       [4, 5]])

## Boolean Indexing

In [69]:
names = np.array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])

In [70]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [71]:
data = np.random.randn(7,4)

In [72]:
data

array([[-0.93540522,  0.89753513, -0.35196612, -1.34973238],
       [ 0.53297625,  1.19882923,  0.46778963,  0.24329565],
       [-0.1292363 , -0.13846967, -0.29641874, -1.18060202],
       [-0.05506795,  1.10026095, -0.63603646,  1.23602117],
       [-0.25212036,  0.98744472, -1.10189491, -0.0380938 ],
       [ 2.24542256,  1.75212285, -0.47069363, -0.97464278],
       [ 0.06525564,  1.05297339, -0.62528988, -0.00639458]])

In [73]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [74]:
data[names=="Bob"]

array([[-0.93540522,  0.89753513, -0.35196612, -1.34973238],
       [-0.05506795,  1.10026095, -0.63603646,  1.23602117]])

In [76]:
data[names=="Bob",2:]

array([[-0.35196612, -1.34973238],
       [-0.63603646,  1.23602117]])

In [88]:
d1 = np.random.randn(3,4)

In [89]:
d1

array([[-1.19198609,  1.35551627,  0.72401869, -0.4430662 ],
       [-1.80866208,  0.70103817,  0.62492958, -0.43614592],
       [-1.80686242,  0.32991142,  0.88172472,  0.48673934]])

In [94]:
b = d1 < -1.0

In [95]:
b

array([[ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False]])

In [96]:
d1[b]

array([-1.19198609, -1.80866208, -1.80686242])

In [110]:
mask = (names == "Bob") | (names == "Will")

In [111]:
mask

array([ True, False,  True,  True,  True, False, False])

In [112]:
data[mask].shape

(4, 4)

In [113]:
d1 = abs(np.random.randn(7,4))

In [114]:
d1

array([[0.24632108, 0.10518961, 0.11150074, 0.46293589],
       [0.53915592, 0.18867673, 1.17790117, 0.22355283],
       [0.49067985, 1.21862094, 0.11105186, 0.42000394],
       [1.13542252, 1.29011117, 0.57091173, 0.81527992],
       [0.66391354, 0.54688314, 0.64161959, 0.31327056],
       [1.59050145, 0.40471605, 0.78245738, 1.26715495],
       [0.66472492, 1.17805478, 0.72054755, 0.4707474 ]])

In [115]:
d1.shape

(7, 4)

In [116]:
d1[mask]

array([[0.24632108, 0.10518961, 0.11150074, 0.46293589],
       [0.49067985, 1.21862094, 0.11105186, 0.42000394],
       [1.13542252, 1.29011117, 0.57091173, 0.81527992],
       [0.66391354, 0.54688314, 0.64161959, 0.31327056]])

In [117]:
d1[mask].shape

(4, 4)

In [121]:
data[data < 0] = 0

In [122]:
data

array([[0.        , 0.89753513, 0.        , 0.        ],
       [0.53297625, 1.19882923, 0.46778963, 0.24329565],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.10026095, 0.        , 1.23602117],
       [0.        , 0.98744472, 0.        , 0.        ],
       [2.24542256, 1.75212285, 0.        , 0.        ],
       [0.06525564, 1.05297339, 0.        , 0.        ]])

In [123]:
data[names != 'Joe'] = 7

In [124]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.53297625, 1.19882923, 0.46778963, 0.24329565],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [2.24542256, 1.75212285, 0.        , 0.        ],
       [0.06525564, 1.05297339, 0.        , 0.        ]])

In [125]:
names != 'Joe'

array([ True, False,  True,  True,  True, False, False])