In [1]:
import numpy as np

In [2]:
# Print the reverse of the strings present in given below list

In [4]:
k = ['harish','saras','lucky','pandas']

for i in k:
    print(i[::-1])

hsirah
saras
ykcul
sadnap


In [7]:
# print every letter of your name

myName = "Mohd Faisal Moinuddin Naushad Suleman"

for i in myName:
    print(i, end=" ")

M o h d   F a i s a l   M o i n u d d i n   N a u s h a d   S u l e m a n 

In [9]:
#Print the elements having even length from the list

m = ['dogg','cat','elephant','horse']

for i in m:
    if len(i)%2 == 0:
        print(i)

dogg
elephant


In [23]:
# print the same repeated digit numbers from 1 to 100

def hasRepeatedDigits(param1):
    num = str(param1)
    return len(set(num)) < len(num)

In [29]:
repeatedMatrix = np.array([x for x in range(1,101) if hasRepeatedDigits(x)])

In [27]:
str1= "44"
check1 = set(str1)
check2 = len(check1)

print(check1)
print(check2)

{'4'}
1


In [30]:
repeatedMatrix.dtype

dtype('int64')

In [31]:
repeatedMatrix

array([ 11,  22,  33,  44,  55,  66,  77,  88,  99, 100])

In [32]:
k = ['harish','saras','lucky','pandas']

for i in k:
    print(f"{i} - {len(i)}")

harish - 6
saras - 5
lucky - 5
pandas - 6


### Basic Indexing and Slicing

In [37]:
arr = np.arange(1,11)

In [51]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
addMatrix = arr + repeatedMatrix

In [53]:
addMatrix

array([ 12,  24,  36,  48,  60,  72,  84,  96, 108, 110])

In [57]:
addMatrix[4] = addMatrix[4] + 4

In [58]:
addMatrix

array([ 12,  24,  36,  48,  64,  72,  84,  96, 108, 110])

In [59]:
addMatrix[::-1]

array([110, 108,  96,  84,  72,  64,  48,  36,  24,  12])

In [60]:
addMatrix[2:5]

array([36, 48, 64])

In [61]:
addMatrix[5:7] = 999

In [62]:
addMatrix

array([ 12,  24,  36,  48,  64, 999, 999,  96, 108, 110])

In [63]:
arr_slic = addMatrix[5:7]

In [64]:
arr_slic

array([999, 999])

In [65]:
arr_slic[1] = 12345

In [66]:
addMatrix

array([   12,    24,    36,    48,    64,   999, 12345,    96,   108,
         110])

In [67]:
arr_slic

array([  999, 12345])

In [86]:
matrix2DArr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [87]:
matrix2DArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
matrix2DArr[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
matrix2DArr[1,1]

5

In [90]:
matrix2DArr[1,1] == matrix2DArr[1][1]

True

In [85]:
matrix2DArr[1][1]

5